[tool.bumpversion]
current_version = "0.15.0"
commit = true

[[tool.bumpversion.files]]
filename = "cafleet/pyproject.toml"
search   = "version = \"{current_version}\""
replace  = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "uv.lock"
search   = """
name = \"cafleet\"
version = \"{current_version}\""""
replace   = """
name = \"cafleet\"
version = \"{new_version}\""""
