"""skill_installs

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-04 11:23:41.911647

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skill_installs",
        sa.Column("coding_agent", sa.String(), nullable=False),
        sa.Column("cafleet_version", sa.String(), nullable=False),
        sa.Column("installed_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("coding_agent"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skill_installs")
    # ### end Alembic commands ###
