[package]
name = "cafleet"
version = "0.22.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
chrono = "0.4"
include_dir = "0.7"
nix = { version = "0.29", features = ["signal"] }
refinery = { version = "0.8", features = ["rusqlite"] }
regex = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
rust-embed = "8"
serde_json = { version = "1", features = ["preserve_order"] }

[dev-dependencies]
sha2 = "0.10"
tempfile = "3"
