"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-04-11 16:28:37.776617

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("api_key_hash", sa.String(), nullable=False),
        sa.Column("owner_sub", sa.String(), nullable=False),
        sa.Column("key_prefix", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("api_key_hash"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index("idx_api_keys_owner", ["owner_sub"], unique=False)

    op.create_table(
        "agents",
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("registered_at", sa.String(), nullable=False),
        sa.Column("deregistered_at", sa.String(), nullable=True),
        sa.Column("agent_card_json", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["api_keys.api_key_hash"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.create_index(
            "idx_agents_tenant_status", ["tenant_id", "status"], unique=False
        )

    op.create_table(
        "tasks",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("context_id", sa.String(), nullable=False),
        sa.Column("from_agent_id", sa.String(), nullable=False),
        sa.Column("to_agent_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("status_state", sa.String(), nullable=False),
        sa.Column("status_timestamp", sa.String(), nullable=False),
        sa.Column("task_json", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["context_id"], ["agents.agent_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(
            "idx_tasks_context_status_ts",
            ["context_id", "status_timestamp"],
            unique=False,
        )
        batch_op.create_index(
            "idx_tasks_from_agent_status_ts",
            ["from_agent_id", "status_timestamp"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("idx_tasks_from_agent_status_ts")
        batch_op.drop_index("idx_tasks_context_status_ts")

    op.drop_table("tasks")
    with op.batch_alter_table("agents", schema=None) as batch_op:
        batch_op.drop_index("idx_agents_tenant_status")

    op.drop_table("agents")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index("idx_api_keys_owner")

    op.drop_table("api_keys")
    # ### end Alembic commands ###
