"""Tests for auth.py — API key authentication dependency.

Covers ``get_authenticated_agent`` and ``get_registration_tenant`` FastAPI
dependencies. Exercises Bearer token extraction, SHA-256 tenant lookup via
the SQL-backed RegistryStore, and HTTP 401 for every invalid/missing auth
scenario.

The Redis-backed predecessor used a ``redis_client`` fixture and hand-rolled
``HSET`` helpers. The SQL rewrite drops those in favor of the ``store``
fixture from conftest.py and seeds data via ``store.create_api_key`` /
``store.create_agent``. API keys are now generated by the store (random
16-byte hex) rather than pinned to fixed constants.
"""

import hashlib
from unittest.mock import MagicMock

import pytest
from fastapi import HTTPException

from hikyaku_registry.auth import get_authenticated_agent, get_registration_tenant


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_tenant_request(
    authorization: str | None = None,
    x_agent_id: str | None = None,
) -> MagicMock:
    """Construct a mock Request with Authorization and X-Agent-Id headers."""
    request = MagicMock()
    headers: dict[str, str] = {}
    if authorization is not None:
        headers["authorization"] = authorization
    if x_agent_id is not None:
        headers["x-agent-id"] = x_agent_id
    request.headers = headers
    return request


async def _new_key(store, owner_sub: str = "auth0|test-owner") -> tuple[str, str]:
    """Create a fresh API key and return ``(api_key, tenant_id)``."""
    api_key, tenant_id, _ = await store.create_api_key(owner_sub)
    return api_key, tenant_id


async def _new_agent(store, api_key: str, name: str = "test-agent") -> str:
    """Create an agent under the given api_key and return its agent_id."""
    record = await store.create_agent(name, "test agent", None, api_key=api_key)
    return record["agent_id"]


# ===========================================================================
# Multi-tenant auth tests
# ===========================================================================


class TestMultiTenantAuth:
    """``get_authenticated_agent`` with multi-tenant support.

    Requires both ``Authorization`` (Bearer api_key) and ``X-Agent-Id``
    headers and returns a ``(agent_id, tenant_id)`` tuple. Every failure
    path must raise ``HTTPException(status_code=401)``.
    """

    async def test_valid_auth_returns_agent_id_and_tenant_id_tuple(self, store):
        """Valid Bearer + X-Agent-Id with matching tenant returns (agent_id, tenant_id)."""
        api_key, tenant_id = await _new_key(store)
        agent_id = await _new_agent(store, api_key)
        request = _make_tenant_request(
            authorization=f"Bearer {api_key}",
            x_agent_id=agent_id,
        )

        result = await get_authenticated_agent(request, store)

        assert result == (agent_id, tenant_id)

    async def test_tenant_id_equals_sha256_of_api_key(self, store):
        """The tenant_id in the returned tuple equals SHA256(api_key)."""
        api_key, _ = await _new_key(store)
        agent_id = await _new_agent(store, api_key)
        request = _make_tenant_request(
            authorization=f"Bearer {api_key}",
            x_agent_id=agent_id,
        )

        _, tenant_id = await get_authenticated_agent(request, store)

        assert tenant_id == hashlib.sha256(api_key.encode()).hexdigest()

    async def test_missing_authorization_header_raises_401(self, store):
        """Missing Authorization header raises HTTP 401."""
        request = _make_tenant_request(authorization=None, x_agent_id="agent-001")

        with pytest.raises(HTTPException) as exc_info:
            await get_authenticated_agent(request, store)

        assert exc_info.value.status_code == 401

    async def test_missing_x_agent_id_header_raises_401(self, store):
        """Missing X-Agent-Id header raises HTTP 401."""
        api_key, _ = await _new_key(store)
        request = _make_tenant_request(
            authorization=f"Bearer {api_key}",
            x_agent_id=None,
        )

        with pytest.raises(HTTPException) as exc_info:
            await get_authenticated_agent(request, store)

        assert exc_info.value.status_code == 401

    async def test_revoked_api_key_raises_401(self, store):
        """An API key whose row is status='revoked' → 401 at is_api_key_active."""
        api_key, tenant_id = await _new_key(store)
        agent_id = await _new_agent(store, api_key)
        await store.revoke_api_key(tenant_id, "auth0|test-owner")
        request = _make_tenant_request(
            authorization=f"Bearer {api_key}",
            x_agent_id=agent_id,
        )

        with pytest.raises(HTTPException) as exc_info:
            await get_authenticated_agent(request, store)

        assert exc_info.value.status_code == 401

    async def test_unknown_api_key_raises_401(self, store):
        """A Bearer token whose hash has no api_keys row → 401."""
        # Never created via store.create_api_key — no matching row.
        fake_api_key = "hky_" + "0" * 32
        request = _make_tenant_request(
            authorization=f"Bearer {fake_api_key}",
            x_agent_id="agent-any",
        )

        with pytest.raises(HTTPException) as exc_info:
            await get_authenticated_agent(request, store)

        assert exc_info.value.status_code == 401

    async def test_agent_in_different_tenant_raises_401(self, store):
        """X-Agent-Id belongs to a different tenant than the API key → 401."""
        api_key_a, _ = await _new_key(store, owner_sub="auth0|owner-a")
        api_key_b, _ = await _new_key(store, owner_sub="auth0|owner-b")
        agent_in_b = await _new_agent(store, api_key_b, name="agent-in-b")
        # Request uses tenant A's key but references tenant B's agent
        request = _make_tenant_request(
            authorization=f"Bearer {api_key_a}",
            x_agent_id=agent_in_b,
        )

        with pytest.raises(HTTPException) as exc_info:
            await get_authenticated_agent(request, store)

        assert exc_info.value.status_code == 401

    async def test_nonexistent_agent_id_raises_401(self, store):
        """X-Agent-Id that doesn't exist at all raises HTTP 401."""
        api_key, _ = await _new_key(store)
        request = _make_tenant_request(
            authorization=f"Bearer {api_key}",
            x_agent_id="agent-does-not-exist",
        )

        with pytest.raises(HTTPException) as exc_info:
            await get_authenticated_agent(request, store)

        assert exc_info.value.status_code == 401

    async def test_malformed_authorization_basic_raises_401(self, store):
        """'Basic' scheme instead of 'Bearer' raises HTTP 401."""
        request = _make_tenant_request(
            authorization="Basic dXNlcjpwYXNz",
            x_agent_id="agent-001",
        )

        with pytest.raises(HTTPException) as exc_info:
            await get_authenticated_agent(request, store)

        assert exc_info.value.status_code == 401

    async def test_empty_bearer_token_raises_401(self, store):
        """'Bearer ' with empty token raises HTTP 401."""
        request = _make_tenant_request(
            authorization="Bearer ",
            x_agent_id="agent-001",
        )

        with pytest.raises(HTTPException) as exc_info:
            await get_authenticated_agent(request, store)

        assert exc_info.value.status_code == 401

    async def test_multiple_agents_same_tenant_each_resolves(self, store):
        """Multiple agents sharing the same API key each authenticate correctly."""
        api_key, tenant_id = await _new_key(store)
        agent_ids = [
            await _new_agent(store, api_key, name=f"agent-mt-{i}") for i in range(3)
        ]

        for aid in agent_ids:
            request = _make_tenant_request(
                authorization=f"Bearer {api_key}",
                x_agent_id=aid,
            )
            result = await get_authenticated_agent(request, store)
            assert result == (aid, tenant_id)

    async def test_agents_in_different_tenants_isolated(self, store):
        """Agents in different tenants cannot authenticate with each other's API key."""
        api_key_a, tenant_a = await _new_key(store, owner_sub="auth0|owner-a")
        api_key_b, _ = await _new_key(store, owner_sub="auth0|owner-b")
        agent_a = await _new_agent(store, api_key_a, name="agent-tenant-a")
        agent_b = await _new_agent(store, api_key_b, name="agent-tenant-b")

        # Agent A with its own key → OK
        req_a = _make_tenant_request(
            authorization=f"Bearer {api_key_a}",
            x_agent_id=agent_a,
        )
        result = await get_authenticated_agent(req_a, store)
        assert result == (agent_a, tenant_a)

        # Agent B with Agent A's key → 401
        req_cross = _make_tenant_request(
            authorization=f"Bearer {api_key_a}",
            x_agent_id=agent_b,
        )
        with pytest.raises(HTTPException) as exc_info:
            await get_authenticated_agent(req_cross, store)
        assert exc_info.value.status_code == 401


# ===========================================================================
# get_registration_tenant tests
# ===========================================================================


class TestRegistrationTenant:
    """``get_registration_tenant`` helper for the registration flow.

    Always requires a valid, active API key. Returns
    ``(api_key, api_key_hash)``.
    """

    async def test_valid_token_existing_tenant_returns_tuple(self, store):
        """Valid Bearer with active apikey record returns (api_key, api_key_hash)."""
        api_key, tenant_id = await _new_key(store)
        request = _make_tenant_request(authorization=f"Bearer {api_key}")

        result = await get_registration_tenant(request, store)

        assert result == (api_key, tenant_id)

    async def test_unknown_api_key_raises_401(self, store):
        """Valid-looking Bearer but no api_keys row → 401."""
        fake_api_key = "hky_" + "1" * 32
        request = _make_tenant_request(authorization=f"Bearer {fake_api_key}")

        with pytest.raises(HTTPException) as exc_info:
            await get_registration_tenant(request, store)

        assert exc_info.value.status_code == 401

    async def test_revoked_api_key_raises_401(self, store):
        """A previously-valid API key that's now revoked → 401."""
        api_key, tenant_id = await _new_key(store)
        await store.revoke_api_key(tenant_id, "auth0|test-owner")
        request = _make_tenant_request(authorization=f"Bearer {api_key}")

        with pytest.raises(HTTPException) as exc_info:
            await get_registration_tenant(request, store)

        assert exc_info.value.status_code == 401

    async def test_malformed_auth_basic_raises_401(self, store):
        """'Basic' scheme instead of 'Bearer' raises HTTP 401."""
        request = _make_tenant_request(authorization="Basic dXNlcjpwYXNz")

        with pytest.raises(HTTPException) as exc_info:
            await get_registration_tenant(request, store)

        assert exc_info.value.status_code == 401

    async def test_malformed_auth_empty_token_raises_401(self, store):
        """'Bearer ' with empty token raises HTTP 401."""
        request = _make_tenant_request(authorization="Bearer ")

        with pytest.raises(HTTPException) as exc_info:
            await get_registration_tenant(request, store)

        assert exc_info.value.status_code == 401

    async def test_malformed_auth_no_scheme_raises_401(self, store):
        """Token without scheme prefix raises HTTP 401."""
        request = _make_tenant_request(
            authorization="hky_a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4"
        )

        with pytest.raises(HTTPException) as exc_info:
            await get_registration_tenant(request, store)

        assert exc_info.value.status_code == 401

    async def test_returns_correct_hash_for_api_key(self, store):
        """The returned api_key_hash is the SHA256 hex digest of the api_key."""
        api_key, _ = await _new_key(store)
        request = _make_tenant_request(authorization=f"Bearer {api_key}")

        returned_api_key, api_key_hash = await get_registration_tenant(request, store)

        assert returned_api_key == api_key
        assert api_key_hash == hashlib.sha256(api_key.encode()).hexdigest()
